[package]
name = "httpclient"
version = "0.1.0"
authors = ["Mathias Flagey <mathias.flagey@etu.umontpellier.fr>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", features = ["blocking", "json"] }