[package]
name = "riktl"
version = "0.1.0"
authors = ["Julian Labatut <julian.labatut@etu.umontpellier.fr>", "Mathias Flagey <mathias.flagey@etu.umontpellier.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
